###S3 CSV 파일 읽어 DB에 저장
POST http://localhost:8080/csv_read

<> 2022-12-02T170210.200.txt

### 첫 문제
POST http://localhost:8080/exam
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlVTRVIiLCJhdWQiOiJhc2ZkIiwiZXhwIjoxNjcwMzEzNjEzfQ.U2GwfpxYmih6LBNSlXFr2D7--oPKprRgL_YNPENx4RPCvZXaDeGwYLs7K22Wq-kHK7L7HhRYWXY01j04jo2EVw

{
  "exam" : "READING"
}

<> 2022-12-02T170510.500.json

### 다음 문제
POST http://localhost:8080/exam/next
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiYXV0aCI6IlVTRVIiLCJhdWQiOiJhc2ZkIiwiZXhwIjoxNjcwMzEzNjc5fQ.e_RgVPkwGBsk4XLGhuaxoygoxmZxJCebRLKaYbIbsaWso28VLHfL34pFPJHycP_g3kMXKw8VXtbI-3qymjFPvQ

{
  "examId" : "28",
  "myAnswer" : "1",
  "number" : "6",
  "examPaper" : "1"
}

<> 2022-12-02T170458.500.json