###S3 CSV 파일 읽어 DB에 저장
POST http://localhost:8080/csv_read

<> 2022-12-02T170210.200.txt

### 첫 문제
POST http://localhost:8080/exam
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IlVTRVIiLCJhdWQiOiJhc2ZkIiwiZXhwIjoxNjY5OTY5MjQ3fQ.4OTJv0iGM3JRVbwtFPzzUcWrQVMketR3YKJpriJuRfq7RK_FfaAZdzaVOj7jQtvg0SMPzUJ0xZ9Bz9aqv9LiYg

{
  "exam" : "READING"
}

<> 2022-12-02T170510.500.json

### 다음 문제
POST http://localhost:8080/exam/next
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiYXV0aCI6IlVTRVIiLCJhdWQiOiJhc2ZkIiwiZXhwIjoxNjY5OTY5MjQ3fQ.4OTJv0iGM3JRVbwtFPzzUcWrQVMketR3YKJpriJuRfq7RK_FfaAZdzaVOj7jQtvg0SMPzUJ0xZ9Bz9aqv9LiYg

{
  "examId" : "28",
  "myAnswer" : "1",
  "number" : "1",
  "examPaper" : "14"
}

<> 2022-12-02T170458.500.json