spring:
#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: 'false'
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://jkeduexam.cn3flekcns70.ap-northeast-2.rds.amazonaws.com:3306/jkedu?serverTimezone=Asia/Seoul
#    username: admin
#    password: a123456789
#root:
#  key: AnyKeyYouWantTo
#server:
#  port: '8080'
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /db
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
cloud:
  aws:
    s3:
      bucket: jkedu.question
    credentials:
      access-key: AKIA4OTF2RFBNW42IR5C
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
    org:
      hibernate:
        type:
          descriptor:
            sql: debug
springdoc:
  swagger-ui:
    path: /springdocs-demo
    use-root-path: true
  version: 'v1'